LaClient/Pages/DetailedCollection.cshtml.cs
namespace LaClient.Pages
{
    using System.Text.Json;
    using LaClient.DTO;
    using LaClient.Materials;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.RazorPages;

    public class DetailTokenModel : PageModel
    {
        private const int PageSize = 12;

        private static readonly string     NftApiUrl = $"{ProjectStaticValue.Host}/api/Nft/";
        private                 HttpClient client;
        
        private string? nftApiHandler;

        /*public string       Query = "";*/
        public List<NftDto> NftDto;

        public DetailTokenModel()
        {
            this.client = new HttpClient();
            this.NftDto = new List<NftDto>();
        }

        [FromQuery(Name = "page")] public int          CurrentPage { get; set; } = 1;
        public                            List<string> PageLink    { get; set; } = new();
        public                            string?      Collection  { get; set; }
        public async Task<IActionResult> OnGetAsync(string? collection, string query)
        {
            this.Collection    = collection;
            this.nftApiHandler = $"GetTotalNftByCollection/{collection}";
            var responseTotalRecords = await this.client.GetAsync(NftApiUrl + this.nftApiHandler);
            var dataTotalRecords     = await responseTotalRecords.Content.ReadAsStringAsync();
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };
            var totalRecords = JsonSerializer.Deserialize<int>(dataTotalRecords, options);
            var total        = this.CalcPageCount(totalRecords);

            if (this.CurrentPage < 1 || this.CurrentPage > total)
            {
                return this.RedirectToPage("Error");
            }

            var page = new PageLink(PageSize);
            this.PageLink = page.getLink(this.CurrentPage, totalRecords, "/DetailedCollection/" + collection + "?");

            this.nftApiHandler = $"GetNftByCollection/{collection}/{this.CurrentPage}/{PageSize}";
            var response = await this.client.GetAsync(NftApiUrl + this.nftApiHandler);
            var data     = await response.Content.ReadAsStringAsync();

            this.NftDto = JsonSerializer.Deserialize<List<NftDto>>(data, options)!.ToList();
            if (string.IsNullOrEmpty(query)) return this.Page();
            /*this.Query              = query;*/
            this.nftApiHandler = $"SortNftCollectionByParam/{collection}/{query}/{this.CurrentPage}/{PageSize}";
            var sortResponse = await this.client.GetAsync(NftApiUrl + this.nftApiHandler);
            var sortData     = await sortResponse.Content.ReadAsStringAsync();
            this.NftDto = JsonSerializer.Deserialize<List<NftDto>>(sortData, options)!.ToList();

            return this.Page();
        }

        private int CalcPageCount(int totalRecords)
        {
            var totalPage = totalRecords / PageSize;

            if (totalRecords % PageSize != 0) totalPage++;
            return totalPage;
        }
    }
}

LaClient/Pages/DetailedNft.cshtml.cs
namespace LaClient.Pages;

using System.Text.Json;
using LaAPI.DTO;
using LaClient.DTO;
using LaClient.Materials;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

public class DetailedNft : PageModel
{
    private static readonly string                 NftApiUrl           = $"{ProjectStaticValue.Host}/api/Nft/";
    private static readonly string                 NftCollectionApiUrl = $"{ProjectStaticValue.Host}/api/NftCollections/";
    private static readonly string                 NftSaleApiUrl       = $"{ProjectStaticValue.Host}/api/NftSale/";
    private                 HttpClient             client;
    private                 string                 NftApiHandler;
    private                 string                 NftCollectionApiHandler;
    private                 string                 NftSaleApiHandler;
    private                 JsonSerializerOptions? options = new() { PropertyNameCaseInsensitive = true };

    public DetailedNft() { this.client = new HttpClient(); }
    public NftDto             NftDto     { get; set; }
    public List<NftsSaleDTO>? NftSaleDto { get; set; } = new();
    public async Task<IActionResult> OnGetAsync([FromQuery] string collection, [FromQuery] string id)
    {
        this.NftCollectionApiHandler = "GetNftCollectionByCollection" + "/" + collection;

        // Get response from Nft
        this.NftApiHandler = "GetNftByCollectionAndId" + "/" + collection + "/" + id;
        var nftResponse = await this.client.GetAsync(NftApiUrl + this.NftApiHandler);
        var nftData     = await nftResponse.Content.ReadAsStringAsync();
        var nft         = JsonSerializer.Deserialize<NftDto>(nftData, this.options);

        // Get response from NftCollection
        var collectionResponse = await this.client.GetAsync(NftCollectionApiUrl + this.NftCollectionApiHandler);
        var collectionData     = await collectionResponse.Content.ReadAsStringAsync();
        var nftCollection      = JsonSerializer.Deserialize<NftCollectionDTO>(collectionData, this.options);
        this.NftDto = new NftDto
        {
            slug = nft!.slug, image_url = nft.image_url, token_id = nft.token_id, collection_name = nftCollection!.name, nft_rarity = nft.nft_rarity, nft_return = nft.nft_return, traits = nft.traits
        };


        this.NftSaleApiHandler = "GetNftSaleByCollection" + "/" + this.NftDto.slug + "/" + this.NftDto.token_id;
        // Get response from NftSale
        var saleResponse = await this.client.GetAsync(NftSaleApiUrl + this.NftSaleApiHandler);
        var saleData     = await saleResponse.Content.ReadAsStringAsync();
        this.NftSaleDto = JsonSerializer.Deserialize<List<NftsSaleDTO>>(saleData, this.options);

        return this.Page();
    }
}

LaClient/Pages/Error.cshtml.cs
namespace LaClient.Pages
{
    using System.Diagnostics;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.RazorPages;

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger) { this._logger = logger; }
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(this.RequestId);

        public void OnGet() { this.RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier; }
    }
}

LaClient/Pages/FAQ.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LaClient.Pages;

public class FAQ : PageModel
{
    public void OnGet()
    {
        
    }
}

LaClient/Pages/Index.cshtml.cs
namespace LaClient.Pages
{
    using System.Text.Json;
    using LaAPI.DTO;
    using LaClient.Materials;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.RazorPages;
    using ClosedXML.Excel;
    using ExcelDataReader;

    public class IndexModel : PageModel
    {
        private static readonly string NftCollectionApiUrl = $"{ProjectStaticValue.Host}/api/NftCollections/";
        private                 HttpClient client;
        private                 string NftCollectionApiHandler;
        private const           int NumberOfRecord = 5;
        private                 List<NftCollectionDTO>? CachedNftCollectionDtos;

        public List<NftCollectionDTO> TopReturnCollectionDtos;
        public List<NftCollectionDTO> TopFollowersCollectionDtos;
        public NftCollectionDTO?      TopOwnerNftCollectionDto;
        public NftCollectionDTO?      TopSaleNftCollectionDto;
        public NftCollectionDTO?      TopReturnNftCollectionDto;

        private List<NftCollectionDTO>? AllNftCollectionDto;
        private JsonSerializerOptions?  options;

        public IndexModel()
        {
            this.client = new HttpClient();
            this.options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };
        }

        public async Task<IActionResult> OnGetAsync(string searchItem)
        {
            this.NftCollectionApiHandler = "GetAllCollections";
            var listNftCollectionResponse =
                await this.client.GetAsync(NftCollectionApiUrl + this.NftCollectionApiHandler);
            var dataNftCollection = await listNftCollectionResponse.Content.ReadAsStringAsync();

            this.CachedNftCollectionDtos =
                JsonSerializer.Deserialize<List<NftCollectionDTO>>(dataNftCollection, this.options);
            this.TopReturnCollectionDtos = this.CachedNftCollectionDtos!
                .OrderByDescending(dto => dto.nft_collection_return).Take(NumberOfRecord)
                .ToList();
            this.TopFollowersCollectionDtos = this.CachedNftCollectionDtos!
                .OrderByDescending(dto => dto.twitter_followers).Take(NumberOfRecord)
                .ToList();
            this.NftCollectionApiHandler = "GetTopSaleNftCollection";
            var topSaleCollectionResponse =
                await this.client.GetAsync(NftCollectionApiUrl + this.NftCollectionApiHandler);
            var dataTopSaleCollection = await topSaleCollectionResponse.Content.ReadAsStringAsync();
            this.TopSaleNftCollectionDto =
                JsonSerializer.Deserialize<NftCollectionDTO>(dataTopSaleCollection, this.options);

            this.NftCollectionApiHandler = "GetTopOwnerNftCollection";
            var topOwnerCollectionResponse =
                await this.client.GetAsync(NftCollectionApiUrl + this.NftCollectionApiHandler);
            var dataTopOwnerCollection = await topOwnerCollectionResponse.Content.ReadAsStringAsync();
            this.TopOwnerNftCollectionDto =
                JsonSerializer.Deserialize<NftCollectionDTO>(dataTopOwnerCollection, this.options);

            this.NftCollectionApiHandler = "GetTopReturnNftCollection";
            var topReturnCollectionResponse =
                await this.client.GetAsync(NftCollectionApiUrl + this.NftCollectionApiHandler);
            var topReturnCollectionData = await topReturnCollectionResponse.Content.ReadAsStringAsync();
            this.TopReturnNftCollectionDto =
                JsonSerializer.Deserialize<NftCollectionDTO>(topReturnCollectionData, this.options);

            return this.Page();
        }

        public async Task<JsonResult> OnPostSearch(string searchTerm)
        {
            this.NftCollectionApiHandler = "GetAllCollections";
            var listNftCollectionResponse =
                await this.client.GetAsync(NftCollectionApiUrl + this.NftCollectionApiHandler);
            var dataNftCollection = await listNftCollectionResponse.Content.ReadAsStringAsync();

            this.AllNftCollectionDto =
                JsonSerializer.Deserialize<List<NftCollectionDTO>>(dataNftCollection, this.options);
            var data = this.AllNftCollectionDto!.Select(dto => dto)
                .Where(dto => dto.name.ToLower().Contains(searchTerm.ToLower())).ToList();
            return new JsonResult(data);
        }

        public async Task<IActionResult> OnGetExport()
        {
            this.NftCollectionApiHandler = "GetAllCollections";
            var listNftCollectionResponse =
                await this.client.GetAsync(NftCollectionApiUrl + this.NftCollectionApiHandler);
            var       dataNftCollection = await listNftCollectionResponse.Content.ReadAsStringAsync();
            this.AllNftCollectionDto =
                JsonSerializer.Deserialize<List<NftCollectionDTO>>(dataNftCollection, this.options);
            var       data     = this.AllNftCollectionDto!.OrderByDescending(dto => dto.nft_collection_return).ToList();
            using var workbook = new XLWorkbook();
            var       ws       = workbook.Worksheets.Add("Sheet1");
            //Header
            ws.Cell(1, 1).Value = "Project";
            ws.Cell(1, 2).Value = "Return Score";
            ws.Cell(1, 3).Value = "Followers";
            ws.Cell(1, 4).Value = "Interaction";
            ws.Cell(1, 5).Value = "Attention";

            ws.Range("A1:G1").Style.Fill.BackgroundColor = XLColor.Alizarin;

            var i = 2;
            foreach (var product in data)
            {
                ws.Cell(i, 1).Value = product.name;
                ws.Cell(i, 2).Value = ((decimal)product.nft_collection_return).ToString("F2");
                ws.Cell(i, 3).Value = ((decimal)product.twitter_followers).ToString("F2");
                ws.Cell(i, 4).Value = ((decimal)product.avg_tweet_interaction).ToString("F2");
                ws.Cell(i, 5).Value = ((decimal)product.avg_tweet_attention).ToString("F2");
                i++;
            }

            i--;

            ws.Cells("A1:E" + i).Style.Border.BottomBorder = XLBorderStyleValues.Thin;
            ws.Cells("A1:E" + i).Style.Border.TopBorder    = XLBorderStyleValues.Thin;
            ws.Cells("A1:E" + i).Style.Border.LeftBorder   = XLBorderStyleValues.Thin;
            ws.Cells("A1:E" + i).Style.Border.RightBorder  = XLBorderStyleValues.Thin;

            using var stream = new MemoryStream();
            workbook.SaveAs(stream);
            var content = stream.ToArray();
            return await Task.FromResult<IActionResult>(this.File(
                content,
                "application/vnd.openxmlformats-officedocument-speadsheetml.sheet",
                "Product.xlsx"
            ));
        }
    }
}

LaClient/Pages/ListedToken.cshtml.cs
namespace LaClient.Pages
{
    using System.Text.Json;
    using LaAPI.DTO;
    using LaClient.Materials;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.RazorPages;

    public class ListedTokenModel : PageModel
    {
        private static readonly string     NftCollectionApiUrl = $"{ProjectStaticValue.Host}/api/NftCollections/GetAllCollections";
        private                 HttpClient client;

        public List<NftCollectionDTO>? NftsCollectionDto;

        public ListedTokenModel() { this.client = new HttpClient(); }

        public async Task<IActionResult> OnGetAsync()
        {
            var response = await this.client.GetAsync(NftCollectionApiUrl);
            var data     = await response.Content.ReadAsStringAsync();
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };
            this.NftsCollectionDto = JsonSerializer.Deserialize<List<NftCollectionDTO>>(data, options);
            return this.Page();
        }
    }
}

LaClient/Pages/Privacy.cshtml.cs
namespace LaClient.Pages
{
    using Microsoft.AspNetCore.Mvc.RazorPages;

    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger) { this._logger = logger; }

        public void OnGet() { }
    }
}

LaClient/Pages/DetailedCollection.cshtml
@page "/DetailedCollection/{collection?}"
@model DetailTokenModel
@{
}
<style>
     body {
            margin-top: 20px;
        }

        .product-card-10 {
            border: 1px solid var(--bs-gray-300)
        }

        .product-card-10 .product-card-image {
            position: relative
        }

        .product-card-10 .badge-ribbon {
            position: absolute;
            top: 10px;
            left: 10px;
            width: 45px;
            height: 45px;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            font-size: 14px;
            text-transform: uppercase;
            background: var(--bs-danger);
            color: var(--bs-white);
            z-index: 1;
            border-radius: 50%
        }

        .product-card-10 .product-media {
            position: relative;
            overflow: hidden;
            border-bottom: 1px solid var(--bs-gray-300)
        }

        .product-card-10 .product-media img {
            transition: ease all .35s;
            transform: scale(1)
        }

        .product-card-10 .product-action {
            padding-top: 8px
        }

        .product-card-10 .product-action .btn {
            width: 40px;
            height: 40px;
            border-radius: 50%;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            background: var(--bs-primary);
            color: var(--bs-white);
            margin: 0 2px;
            padding: 0
        }

        .product-card-10 .product-action .btn:hover {
            background: var(--bs-dark);
            color: var(--bs-white)
        }

        .product-card-10 .product-card-info {
            text-align: center;
            padding: 15px
        }

        .product-card-10 .rating-star {
            font-size: 12px;
            margin-bottom: 5px
        }

        .product-card-10 .product-title {
            font-size: 14px;
            margin: 0
        }

        .product-card-10 .product-title a {
            color: var(--bs-dark)
        }

        .product-card-10 .product-price {
            margin-top: 8px;
            line-height: normal
        }

        .product-card-10:hover .product-media img {
            transform: scale(1.03)
        }

        a {
            text-decoration: none;
        }
        .vertical-nav {
            display: flex;
            flex-direction: column;
        }

    .pagination {
        display: inline-block;
        text-align: center;
    }

        .pagination a {
            color: black;
            float: left;
            padding: 8px 16px;
            text-decoration: none;
        }

            .pagination a.active {
                background-color: sienna;
                color: white;
                border-radius: 5px;
            }

            .pagination a:hover:not(.active) {
                background-color: #ddd;
                border-radius: 5px;
            }
</style>

<div class="container" style="margin-left: 350px; margin-top: 30px">
    <div>
        <form asp-page="./DetailedCollection" asp-page-handler="post">
            <select id="sort-options" class="form-select" aria-label="Default select example" data-collection="@Model.Collection">
                <option value="rarity_asc">Rarity ascending</option>
                <option value="rarity_desc">Rarity descending</option>
                <option value="return_asc">Return ascending</option>
                <option value="return_desc">Return descending</option>
                <option value="id_asc">Id ascending</option>
                <option value="id_desc">Id descending</option>
            </select>
        </form>
    </div>
    &nbsp;
    &nbsp;
    <div class="col-lg-9">
        <div class=row>
            <div class="col-12">
                <!-- Navigation bar content -->
                <div class="row g-3 g-lg-4">
                    @foreach (var nftDto in Model.NftDto)
                    {
                        <div class="col-4 col-lg-3">
                            <div class="product-card-10">
                                <div class="product-card-image">
                                    @* <div class="badge-ribbon"> *@
                                    @*     <span class="badge bg-danger">Sale</span> *@
                                    @* </div> *@
                                    <div class="product-media">
                                        <a asp-page="/DetailedNft" asp-route-collection="@nftDto.slug", asp-route-id="@nftDto.token_id">
                                            <img class="img-fluid"
                                                 src="@nftDto.image_url">
                                        </a>
                                    </div>
                                </div>
                                <div class="product-card-info">
                                    <div class="rating-star text">
                                        <i class="bi bi-star-fill active"></i> <i class="bi bi-star-fill active"></i> <i class="bi bi-star-fill active"></i> <i class="bi bi-star-fill active"></i> <i class="bi bi-star"></i>
                                    </div>
                                    <h6 class="product-title">
                                        <a asp-page="/DetailedNft" asp-route-collection="@nftDto.slug" asp-route-id="@nftDto.token_id">Token ID: @nftDto.token_id</a>
                                    </h6>
                                    <div class="product-price">
                                        <span class="text-primary" style="font-size: x-large">Rarity: @nftDto.nft_rarity.ToString("F2")</span>
                                        <span class="text-primary" style="font-size: x-large">Return: @(Math.Round(nftDto.nft_return * 100, 2))%</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
    <div id="paging">
        <div class="pagination">
            @foreach (var item in Model.PageLink)
            {
                @Html.Raw(item)
            }
        </div>
    </div>
</div>
<script>
    const sortOptions = document.getElementById("sort-options");

    const collection = sortOptions.getAttribute("data-collection");

    sortOptions.addEventListener("change", function() {
        const selectedValue = this.value;
        /*for(let i = 0; i < this.options.length; i++){
            const option = this.options[i]; 
            if(false){
                option.setAttribute('selected', 'selected');
             }else{
               option.removeAttribute('selected');
             }
        }*/        
        const currentUrl = window.location.href;
        const xhr = new XMLHttpRequest();
        xhr.open("GET", "/DetailedCollection/" + collection + "?query=" + selectedValue, true);
        xhr.onreadystatechange = function() {
            if (xhr.readyState === 4 && xhr.status === 200) {
                const queryParams = {};
                queryParams["query"] = selectedValue;
                const updatedUrl = currentUrl.split("?")[0] + "?" + new URLSearchParams(queryParams).toString();
                window.location.href = updatedUrl;
                console.log(xhr.responseText);
            }
        };
        xhr.send();
    });
</script>

LaClient/Pages/Index.cshtml
@page
@model IndexModel
@{
    
}
<style>
	.display-table{
		display: flex;
		gap: 20px;
	}
	.img-top{
	    width: 12vh;
	    height: 12vh;
	}
</style>
<body>
<!-- CONTENT -->
<section id="content">
    <!-- MAIN -->
    <main>
        <!-- Title -->
        <div class="head-title">
            <div class="left">
                <h1>Dashboard</h1>
                <ul class="breadcrumb">
                    <li>
                        <a href="#">Dashboard</a>
                    </li>
                    <li>
                        <i class='bx bx-chevron-right'></i>
                    </li>
                    <li>
                        <a class="active" href="#">Collections</a>
                    </li>
                </ul>
            </div>
            <a asp-page="Index" asp-page-handler="Export" class="btn-download">
                <i class='bx bxs-cloud-download'></i>
                <span class="text">Download</span>
            </a>
        </div>

        <!-- Overall infor -->
        <ul class="box-info" style="padding-left: 0">
            <li>
                <img class="img-top" src="@Model.TopReturnNftCollectionDto!.image_url" alt=""/>
                <span class="text">
                    <h3>@Model.TopReturnNftCollectionDto!.name</h3>
                    <p>Top Return</p>
                </span>
            </li>
            <li>
                <img class="img-top" src="@Model.TopOwnerNftCollectionDto!.image_url" alt=""/>
                <span class="text">
                    <h3>@Model.TopOwnerNftCollectionDto!.stats.num_owners</h3>
                    <p>Top Unique Owner</p>
                </span>
            </li>
            <li>
                <img class="img-top" src="@Model.TopSaleNftCollectionDto!.image_url" alt=""/>
                <span class="text">
                    <h3>@Model.TopSaleNftCollectionDto!.stats.total_sales</h3>
                    <p>Top Sale</p>
                </span>
            </li>
        </ul>

        <!-- Main data -->
        <div class="table-data display-table">
            <div class="order">
                <div class="head">
                    <div class="head">
                        <h3>Ranking by Return</h3>
                        <i class='bx bx-search'></i>
                        <i class='bx bx-filter'></i>
                    </div>
                    <i class='bx bx-search'></i>
                    <i class='bx bx-filter'></i>
                </div>

                <table style="margin-top: -20px">
                    <thead>
                    <tr>
                        <th>Project</th>
                        <th>Ranking</th>
                        <th>Return Score</th>
                    </tr>
                    </thead>
                    <tbody>
                    @for (var i = 0; i < Model.TopReturnCollectionDtos!.Count; i++)
                    {
                        var nftModel = Model.TopReturnCollectionDtos[i];
                        <tr>
                            <td>
                                <img src="@nftModel.image_url">
                                <a asp-page="DetailedCollection" asp-route-collection="@nftModel.id">@nftModel.name</a>
                            </td>
                            <td>@(i + 1)</td>
                            @if(i == 0){
                                <td>
                                    <span class="status pending">@nftModel.nft_collection_return.ToString("F2")</span>
                                </td>
                            }
                            else
                            {
                                <td>
                                    <span class="status completed">@nftModel.nft_collection_return.ToString("F2")</span>
                                </td>
                            }
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
            <div class="order">
                <div class="head">
                    <h3>Ranking by Reputation</h3>
                </div>
                <table>
                    <thead>
                    <tr>
                        <th>Project</th>
                        <th>Ranking</th>
                        <th>Followers</th>
                        <th>Interaction</th>
                    </tr>
                    </thead>
                    <tbody>
                    @for (var i = 0; i < Model.TopFollowersCollectionDtos.Count; i++)
                    {
                        var nftModel = @Model.TopFollowersCollectionDtos[i];
                        <tr>
                            <td>
                                <img src="@nftModel.image_url">
                                <a asp-page="DetailedCollection" asp-route-collection="@nftModel.id">@nftModel.name</a>
                            </td>
                            <td>@(i + 1)</td>
                            @if (i == 0)
                            {
                                <td>  
                                    <span class="status pending">@nftModel.twitter_followers</span>
                                </td>
                                <td>  
                                    <span class="status pending">@nftModel.avg_tweet_interaction.ToString("F2")</span>
                                </td>
                            }
                            else
                            {
                                <td>  
                                    <span class="status completed">@nftModel.twitter_followers</span>
                                </td>
                                <td>  
                                    <span class="status completed">@nftModel.avg_tweet_interaction.ToString("F2")</span>
                                </td>
                              
                            }
                            
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
            <a asp-page="/ListedToken" class="btn-viewall">
                <span class="text">View All Listed Project</span>
            </a>
        </div>
    </main>
    <!-- MAIN -->
</section>
<!-- CONTENT -->
</body>